# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: jrbarrio
  image: https://avatars.githubusercontent.com/u/824810?v=4
spec:
  memberOf: [developers]
---

